// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgaulskfgxpqpakhnukg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnYXVsc2tmZ3hwcXBha2hudWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MjU1NzgsImV4cCI6MjA3MTQwMTU3OH0.nMGO6MndrQ4sd1CdcAPXABuF71E4sBE1fwjxvVAk64c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});